---
roles:
  - name: setup-shell
    src: git@github.com:reubendevries/setup-shell.git
    scm: git
    version: "main"

  - name: rutorrent-role
    src: git@github.com:reubendevries/rutorrent-role.git
    scm: git
    version: "main"

collections:
  - name: community.general
